development: &base
  location: "https://dancit.herokuapp.com/"
  per_page: 20
  fb:
    fb_id: "168713963471223"
    fb_secret: "5806bbbd6ca8047103b24f2e1c706542"
  gg:
    gg_id: "286816984335-pvmq2mjqj7ec698q5v8ppec5k07q51so.apps.googleusercontent.com"
    gg_secret: "R9cxp4etzmXEbl0ymvVmLfAd"

production:
  <<: *base
